---
auth:
  # token=string, the auth token we'll use to ensure a client is legitimate. this is no replacement for sip2 auth!
  token: letmein
websocket:
  # baseUrl=string, a uri, which we will attempt to open a websocket to. this is usually a remote endpoint.
  baseUrl: "ws://127.0.0.1:8765"
sip2:
  # host=string, the source ip address to listen for. usually, this will be localhost
  host: "127.0.0.1"
  # port=number, between 1-65535, the port upon which your sip2 client will attempt to connect
  port: 6043
